# ===================================================
# CORRECTED FILE - Generated by IBD AI (Gemini)
# Original: C:\Users\jaswa\Downloads\FINAL YEAR PROJECT\prototype (2)\prototype\samples\buggy.cpp
# Fixed on: 2026-02-16 22:21:21
# ===================================================

#include <stdio.h>
#include <string.h>

int main() {
  char buffer[10];
  char *long_string = "This is a very long string that might overflow the buffer.";

  // strcpy(buffer, long_string); // BUG: Potential buffer overflow
  strncpy(buffer, long_string, sizeof(buffer) - 1); # FIXED: Use strncpy to prevent buffer overflow
  buffer[sizeof(buffer) - 1] = '\0'; # FIXED: Ensure null termination

  printf("Buffer: %s\n", buffer);

  return 0;
}
