# ===================================================
# CORRECTED FILE - Generated by IBD AI (Gemini)
# Original: C:\Users\jaswa\Downloads\FINAL YEAR PROJECT\prototype (2)\prototype\samples\test_vuln.py
# Fixed on: 2026-02-16 22:21:05
# ===================================================

def calculate_average(numbers):
    """Calculates the average of a list of numbers."""
    total = 0
    for number in numbers:
        total += number  # FIXED: No change needed
    
    if len(numbers) == 0:
        return 0  # FIXED: Return 0 if the list is empty to avoid division by zero
    else:
        average = total / len(numbers)  # FIXED: No change needed
        return average
